### ISSUE TITLE
How to compile with 3rd party libs?

### ISSUE THREAD

**Issue by adconk** [andreaskeller96/HoloLens2-IRTracking#1]
I'm having trouble successfully recompiling the DLL file with third party libs. Are the source files or a compiled version pulled straight from each website manually? Are they installed via vcpkg and the arm64-uwp triplet. Perhaps yet another way? 

This line in particular has me stumped:

Add zlib, libtiff, opencv412d to the project before compilation

**Comment by andreaskeller96** [comment]
The way I have done it is to compile static .lib libraries for windows on arm, then import them into the project. You can either compile them on your own or simply get them from https://github.com/microsoft/HoloLens2ForCV/tree/main/Samples/CameraWithCVAndCalibration/OpenCvInstallArm64-412d. To add them, just drag and drop the linked folder into the project folder. A future version of this tracking will rely on opencv 480 though, so at that point it will need to be compiled manually. I will provide instructions once that version is public.

**Comment by denisshoth** [comment]
I was able to compile the dll for ARM64 but it fails to load dll on HoloLens2. Just wondering if you encountered similar issues in the past, and if so, how you went about debugging them.
'HL2IRToolTrackingSample.exe' (Win32): Unloaded 'U:\USERS\DefaultAccount\AppData\Local\DevelopmentFiles\HL2IRToolTrackingSampleVS.Release_ARM64\HL2IRToolTracking.dll'
Exception thrown at 0x00007FFC0933D5D0 in HL2IRToolTrackingSample.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000006B659FED20.

**Comment by andreaskeller96** [comment]
the only thing that I could think of is that you either do not have enabled research mode, or that you compiled the dll and/or the application in debug mode.

**Comment by denisshoth** [comment]
@andreaskeller96 thank you for your prompt responses. I have tried adding HoloLens2ForCV\Samples\CameraWithCVAndCalibration\OpenCvInstallArm64-412d\x64\vc15\lib\opencv_world412d.lib and compiling as Release. (Btw, your Release build relies on Release version of opencv_word421.lib not opencv_world412d,lib). No luck. So, I have also tried to get opencv libraries compiled for arm64 using vcpkg, both _vcpkg install opencv:arm64-windows_ and _vcpkg install opencv4:arm64-uwp_. They don't provide opencv_world412, but they provide enough libraries to compile your dll. However, the dll still fails to load. If I remove anything related to opencv and just try to load the dll, it works fine. So, it really comes down to opencv. Do you mind to share your opencv libs or how exactly you got them? Is there anything else (other dlls) you had to include (besides libtiff and zlib). It seems like a missing dependency issue.

**Comment by andreaskeller96** [comment]
Are you able to run the sample on your HoloLens without any issues (https://github.com/andreaskeller96/HoloLens2-IRTracking-Sample) ?
I have not tried using vcpkg to compile so I do not know if that is possible. Did you try adding the whole folder HoloLens2ForCV\Samples\CameraWithCVAndCalibration\OpenCvInstallArm64-412d including all headers and libraries?

**Comment by adconk** [comment]
hi @andreaskeller96 - we appreciate your responses on this thread.  However, I don't think either @denisshoth or myself are able to reproduce or recreate your project based on your README and comments here. It's just not possible without a much more detailed README or access to your working developer project via zip or docker file.  Denis used to work at Microsoft on the Hololens team developing eye tracking, he's quite familiar with C++ projects in general.   We actually had two issues that drew interest in recompiling your project.  1) Stop IR Tracking doesn't work. It just continues to function and eat up resources. 2) When we get the transform after adding the first IR tracker, it pretends to be successful even if it isn't. What I mean is that It seems like the Transform + Timestamp should give us an idea of how long ago it last picked up the IR sphere array, but it doesn't.  The Transform shows a valid result, even when the IR Sphere array is hidden from view, and the timestamp keeps updating.  Thought I would share, because we can't recompile to tweak these behaviors.

**Comment by denisshoth** [comment]
@andreaskeller96, just to clarify is HoloLens2ForCV\Samples\CameraWithCVAndCalibration\OpenCvInstallArm64-412d where you got the binaries for your precompiled dll? The hardest part with recompiling OpenCV projects appears to be finding the binary that compiles and works for the specific architecture. So, if you have those binaries, it would really help if you can attached them to your project as well.

**Comment by andreaskeller96** [comment]
@adconk I apologize for the lackluster README and the comments from memory that were not comprehensive. I have updated the repository to rely on OpenCV 4.8.0 and added the required headers and a step-by-step guide in the OpenCV folder on how to compile the necessary binary. As for your your issues:
1) Stop IR Tracking should work now
2) The array returned by the tracking is now correctly setting the final value to 0 if the object has not been detected in the last analyzed frame. If you want the timestamp itself, you can either track it from within unity or you can adjust the array to include the timestamp.


@denisshoth I was going off memory and got it wrong, the binary I used for OpenCV412 was compiled by a colleague since the linked repository only includes the opencv_world412d.lib. I have now included a guide on how to compile OpenCV for HoloLens 2, if this does not work for you I can provide the binary directly to you.

**Comment by adconk** [comment]
hi @andreaskeller96 - thank you so much for the updates the repo.  We'll give it a spin. If there's a chance you might be open to an icebreaker, it would be great to learn more about what you're up to and we can share our efforts too.  I can be reached here if you have interest: andrewconklin (AT) hothintel.com

**Comment by andreaskeller96** [comment]
Sounds great! I have sent you an email and am closing this issue. If you find more issues with the library, feel free to open more tickets or contact me directly!
