### ISSUE TITLE
This is an excellent project. Is there any other way to obtain m_refFrame, which is the root reference coordinate system? I would like to retrieve it within UE4, but I haven't found a suitable method.

### ISSUE THREAD

**Issue by yulaomao** [andreaskeller96/HoloLens2-IRTracking#3]
I tried to retrieve it using the following approach, but there is a consistent offset of approximately 10cm.`m_refFrame=m_locator.GetDefault().CreateStationaryFrameOfReferenceAtCurrentLocation().CoordinateSystem();`

**Comment by andreaskeller96** [comment]
First of all, thank you for the kind words about my project!
In regards to your problem, I unfortunately do not know anything about how Unreal Engine handles the Microsoft XR integration. In Unity this is a call to a Microsoft API, but Unreal might implement its own API for XR related things.
