### ISSUE TITLE
Tracking Integration Fails After Unity and MRTK Updates

### ISSUE THREAD

**Issue by ThomasK-CADS** [andreaskeller96/HoloLens2-IRTracking#4]
Hi,
I recently integrated your tracking solution into my project, and it was working flawlessly! However, after updating my project, the tracking is not working anymore. Here are the key changes I made:

    - Updated Unity from 2019.4.26f to 2022.3.4f
    - Updated MRTK from 2.6.1 to 2.8.3

I suspect one or both of these updates might have introduced compatibility issues or required adjustments to the integration. Is there any adjustment or migration step required to ensure compatibility with the newer Unity or MRTK versions?

I would greatly appreciate any guidance, documentation, or fixes to help resolve this issue. Let me know if you need additional details.
Thank you for your assistance!

**Comment by andreaskeller96** [comment]
Hey,
I’m glad to hear you’re enjoying the project :)
I’ve seen a similar issue recently and I think it has to do with the newest Windows SDK version rather than Unity or mrtk.
I was able to get it running again by simply compiling the DLL from scratch (keep in mind you also need to build opencv).
If you try this, please let me know if this works for you

**Comment by ThomasK-CADS** [comment]
Thank you for your quick response!

Unfortunately I am getting the following error messages when building OpenCV:

<img width="476" alt="image" src="https://github.com/user-attachments/assets/3cedbac8-3728-46f5-9bbb-cc8b772a42d2">


Build started at 15:15...
1>------ Build started: Project: opencv_world, Configuration: Release ARM64 ------
1>   Creating library C:/data/repos/HoloLens2-IRTracking/opencv_Build_dez/lib/Release/opencv_world480.lib and object C:/data/repos/HoloLens2-IRTracking/opencv_Build_dez/lib/Release/opencv_world480.exp
1>libopenjp2.lib(ht_dec.obj) : error LNK2019: unresolved external symbol __popcnt referenced in function opj_t1_ht_decode_cblk
1>C:\data\repos\HoloLens2-IRTracking\opencv_Build_dez\bin\Release\opencv_world480.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "opencv_world.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 15 up-to-date, 0 skipped ==========
========== Build completed at 15:15 and took 05.776 seconds ==========


Do have any idea what might be the cause of the issue?

Thank you in advance!

**Comment by andreaskeller96** [comment]
I’m unsure, but I recently built the opencv DLL myself and it worked following the instructions in the repo step by step. So maybe you can try and rebuild the cmake cache and that might fix it?

**Comment by ThomasK-CADS** [comment]
Thank you for your response and the guidance on the build settings! I realized my earlier mistake—I had overlooked some of the configuration settings during the build process.

- Enable BUILD_opencv_world
- **Disable** BUILD_shared_libs
- **Disable** BUILD_TESTS

While this fixed the build issues, I am still encountering a runtime exception during tracking. The error occurs at the same point as before:

```
System.Exception: Exception of type 'System.Exception' was thrown.
  at HL2IRToolTracking.HL2IRTracking..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at IRToolTracking.StartToolTracking () [0x00000] in <00000000000000000000000000000000>:0 
  at TrackingManager.Start () [0x00000] in <00000000000000000000000000000000>:0 
```

The crash happens during the `StartToolTracking()` function in `IRToolTracking.cs`, specifically when initializing HL2IRTracking:

` toolTracking = new HL2IRTracking();`



I also tried to build your sample project which works fine with Unity 2021. However, if i update to 2022 I am getting the same exception.
Do you have any suggestions on how to solve this issue?

**Comment by ThomasK-CADS** [comment]
Turns out I had to change the UWP CPU architecture in the import settings of HL2IRToolTracking.dll to `ARM64`.

**Comment by andreaskeller96** [comment]
Ah yes I’ve seen that before, awesome that you were able to figure it out!
Is everything working as expected now?

**Comment by ThomasK-CADS** [comment]
Everything works again, thanks for your help!

**Comment by andreaskeller96** [comment]
Perfect, if anything else comes up feel free to open another ticket!
